#ifndef HAL_CONF_EXTRA_H
#define HAL_CONF_EXTRA_
#define HAL_DAC_MODULE_DISABLED
#define HAL_ETH_MODULE_DISABLED
#define HAL_SD_MODULE_DISABLED
#define HAL_EXTI_MODULE_ENABLED
#define HSE_VALUE 8000000U
#define SERIAL_TX_BUFFER_SIZE 4096
#define SERIAL_RX_BUFFER_SIZE 2048

#endif